// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package az

import (
	"context"
	"github.com/lvlcn-t/azctx/config"
	"sync"
)

// Ensure, that CLIMock does implement CLI.
// If this is not the case, regenerate this file with moq.
var _ CLI = &CLIMock{}

// CLIMock is a mock implementation of CLI.
//
//	func TestSomethingThatUsesCLI(t *testing.T) {
//
//		// make and configure a mocked CLI
//		mockedCLI := &CLIMock{
//			LoginFunc: func(ctx context.Context, credential *config.Credential, tenantID string) error {
//				panic("mock out the Login method")
//			},
//			SetSubscriptionFunc: func(ctx context.Context, subscriptionID string) error {
//				panic("mock out the SetSubscription method")
//			},
//		}
//
//		// use mockedCLI in code that requires CLI
//		// and then make assertions.
//
//	}
type CLIMock struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, credential *config.Credential, tenantID string) error

	// SetSubscriptionFunc mocks the SetSubscription method.
	SetSubscriptionFunc func(ctx context.Context, subscriptionID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Credential is the credential argument value.
			Credential *config.Credential
			// TenantID is the tenantID argument value.
			TenantID string
		}
		// SetSubscription holds details about calls to the SetSubscription method.
		SetSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
	}
	lockLogin           sync.RWMutex
	lockSetSubscription sync.RWMutex
}

// Login calls LoginFunc.
func (mock *CLIMock) Login(ctx context.Context, credential *config.Credential, tenantID string) error {
	if mock.LoginFunc == nil {
		panic("CLIMock.LoginFunc: method is nil but CLI.Login was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Credential *config.Credential
		TenantID   string
	}{
		Ctx:        ctx,
		Credential: credential,
		TenantID:   tenantID,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, credential, tenantID)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedCLI.LoginCalls())
func (mock *CLIMock) LoginCalls() []struct {
	Ctx        context.Context
	Credential *config.Credential
	TenantID   string
} {
	var calls []struct {
		Ctx        context.Context
		Credential *config.Credential
		TenantID   string
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// SetSubscription calls SetSubscriptionFunc.
func (mock *CLIMock) SetSubscription(ctx context.Context, subscriptionID string) error {
	if mock.SetSubscriptionFunc == nil {
		panic("CLIMock.SetSubscriptionFunc: method is nil but CLI.SetSubscription was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		SubscriptionID string
	}{
		Ctx:            ctx,
		SubscriptionID: subscriptionID,
	}
	mock.lockSetSubscription.Lock()
	mock.calls.SetSubscription = append(mock.calls.SetSubscription, callInfo)
	mock.lockSetSubscription.Unlock()
	return mock.SetSubscriptionFunc(ctx, subscriptionID)
}

// SetSubscriptionCalls gets all the calls that were made to SetSubscription.
// Check the length with:
//
//	len(mockedCLI.SetSubscriptionCalls())
func (mock *CLIMock) SetSubscriptionCalls() []struct {
	Ctx            context.Context
	SubscriptionID string
} {
	var calls []struct {
		Ctx            context.Context
		SubscriptionID string
	}
	mock.lockSetSubscription.RLock()
	calls = mock.calls.SetSubscription
	mock.lockSetSubscription.RUnlock()
	return calls
}
