// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package az

import (
	"context"
	"github.com/lvlcn-t/azctx/config"
	"sync"
)

// Ensure, that CLIMock does implement CLI.
// If this is not the case, regenerate this file with moq.
var _ CLI = &CLIMock{}

// CLIMock is a mock implementation of CLI.
//
//	func TestSomethingThatUsesCLI(t *testing.T) {
//
//		// make and configure a mocked CLI
//		mockedCLI := &CLIMock{
//			AllowNoSubscriptionsFunc: func(allow bool) CLI {
//				panic("mock out the AllowNoSubscriptions method")
//			},
//			LoginFunc: func(ctx context.Context) error {
//				panic("mock out the Login method")
//			},
//			WithCredentialFunc: func(credential *config.Credential) CLI {
//				panic("mock out the WithCredential method")
//			},
//			WithFederatedTokenFunc: func(token string) CLI {
//				panic("mock out the WithFederatedToken method")
//			},
//			WithSubscriptionFunc: func(subscriptionID string) CLI {
//				panic("mock out the WithSubscription method")
//			},
//			WithTenantFunc: func(tenantID string) CLI {
//				panic("mock out the WithTenant method")
//			},
//		}
//
//		// use mockedCLI in code that requires CLI
//		// and then make assertions.
//
//	}
type CLIMock struct {
	// AllowNoSubscriptionsFunc mocks the AllowNoSubscriptions method.
	AllowNoSubscriptionsFunc func(allow bool) CLI

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context) error

	// WithCredentialFunc mocks the WithCredential method.
	WithCredentialFunc func(credential *config.Credential) CLI

	// WithFederatedTokenFunc mocks the WithFederatedToken method.
	WithFederatedTokenFunc func(token string) CLI

	// WithSubscriptionFunc mocks the WithSubscription method.
	WithSubscriptionFunc func(subscriptionID string) CLI

	// WithTenantFunc mocks the WithTenant method.
	WithTenantFunc func(tenantID string) CLI

	// calls tracks calls to the methods.
	calls struct {
		// AllowNoSubscriptions holds details about calls to the AllowNoSubscriptions method.
		AllowNoSubscriptions []struct {
			// Allow is the allow argument value.
			Allow bool
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// WithCredential holds details about calls to the WithCredential method.
		WithCredential []struct {
			// Credential is the credential argument value.
			Credential *config.Credential
		}
		// WithFederatedToken holds details about calls to the WithFederatedToken method.
		WithFederatedToken []struct {
			// Token is the token argument value.
			Token string
		}
		// WithSubscription holds details about calls to the WithSubscription method.
		WithSubscription []struct {
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
		// WithTenant holds details about calls to the WithTenant method.
		WithTenant []struct {
			// TenantID is the tenantID argument value.
			TenantID string
		}
	}
	lockAllowNoSubscriptions sync.RWMutex
	lockLogin                sync.RWMutex
	lockWithCredential       sync.RWMutex
	lockWithFederatedToken   sync.RWMutex
	lockWithSubscription     sync.RWMutex
	lockWithTenant           sync.RWMutex
}

// AllowNoSubscriptions calls AllowNoSubscriptionsFunc.
func (mock *CLIMock) AllowNoSubscriptions(allow bool) CLI {
	if mock.AllowNoSubscriptionsFunc == nil {
		panic("CLIMock.AllowNoSubscriptionsFunc: method is nil but CLI.AllowNoSubscriptions was just called")
	}
	callInfo := struct {
		Allow bool
	}{
		Allow: allow,
	}
	mock.lockAllowNoSubscriptions.Lock()
	mock.calls.AllowNoSubscriptions = append(mock.calls.AllowNoSubscriptions, callInfo)
	mock.lockAllowNoSubscriptions.Unlock()
	return mock.AllowNoSubscriptionsFunc(allow)
}

// AllowNoSubscriptionsCalls gets all the calls that were made to AllowNoSubscriptions.
// Check the length with:
//
//	len(mockedCLI.AllowNoSubscriptionsCalls())
func (mock *CLIMock) AllowNoSubscriptionsCalls() []struct {
	Allow bool
} {
	var calls []struct {
		Allow bool
	}
	mock.lockAllowNoSubscriptions.RLock()
	calls = mock.calls.AllowNoSubscriptions
	mock.lockAllowNoSubscriptions.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *CLIMock) Login(ctx context.Context) error {
	if mock.LoginFunc == nil {
		panic("CLIMock.LoginFunc: method is nil but CLI.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedCLI.LoginCalls())
func (mock *CLIMock) LoginCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// WithCredential calls WithCredentialFunc.
func (mock *CLIMock) WithCredential(credential *config.Credential) CLI {
	if mock.WithCredentialFunc == nil {
		panic("CLIMock.WithCredentialFunc: method is nil but CLI.WithCredential was just called")
	}
	callInfo := struct {
		Credential *config.Credential
	}{
		Credential: credential,
	}
	mock.lockWithCredential.Lock()
	mock.calls.WithCredential = append(mock.calls.WithCredential, callInfo)
	mock.lockWithCredential.Unlock()
	return mock.WithCredentialFunc(credential)
}

// WithCredentialCalls gets all the calls that were made to WithCredential.
// Check the length with:
//
//	len(mockedCLI.WithCredentialCalls())
func (mock *CLIMock) WithCredentialCalls() []struct {
	Credential *config.Credential
} {
	var calls []struct {
		Credential *config.Credential
	}
	mock.lockWithCredential.RLock()
	calls = mock.calls.WithCredential
	mock.lockWithCredential.RUnlock()
	return calls
}

// WithFederatedToken calls WithFederatedTokenFunc.
func (mock *CLIMock) WithFederatedToken(token string) CLI {
	if mock.WithFederatedTokenFunc == nil {
		panic("CLIMock.WithFederatedTokenFunc: method is nil but CLI.WithFederatedToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockWithFederatedToken.Lock()
	mock.calls.WithFederatedToken = append(mock.calls.WithFederatedToken, callInfo)
	mock.lockWithFederatedToken.Unlock()
	return mock.WithFederatedTokenFunc(token)
}

// WithFederatedTokenCalls gets all the calls that were made to WithFederatedToken.
// Check the length with:
//
//	len(mockedCLI.WithFederatedTokenCalls())
func (mock *CLIMock) WithFederatedTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockWithFederatedToken.RLock()
	calls = mock.calls.WithFederatedToken
	mock.lockWithFederatedToken.RUnlock()
	return calls
}

// WithSubscription calls WithSubscriptionFunc.
func (mock *CLIMock) WithSubscription(subscriptionID string) CLI {
	if mock.WithSubscriptionFunc == nil {
		panic("CLIMock.WithSubscriptionFunc: method is nil but CLI.WithSubscription was just called")
	}
	callInfo := struct {
		SubscriptionID string
	}{
		SubscriptionID: subscriptionID,
	}
	mock.lockWithSubscription.Lock()
	mock.calls.WithSubscription = append(mock.calls.WithSubscription, callInfo)
	mock.lockWithSubscription.Unlock()
	return mock.WithSubscriptionFunc(subscriptionID)
}

// WithSubscriptionCalls gets all the calls that were made to WithSubscription.
// Check the length with:
//
//	len(mockedCLI.WithSubscriptionCalls())
func (mock *CLIMock) WithSubscriptionCalls() []struct {
	SubscriptionID string
} {
	var calls []struct {
		SubscriptionID string
	}
	mock.lockWithSubscription.RLock()
	calls = mock.calls.WithSubscription
	mock.lockWithSubscription.RUnlock()
	return calls
}

// WithTenant calls WithTenantFunc.
func (mock *CLIMock) WithTenant(tenantID string) CLI {
	if mock.WithTenantFunc == nil {
		panic("CLIMock.WithTenantFunc: method is nil but CLI.WithTenant was just called")
	}
	callInfo := struct {
		TenantID string
	}{
		TenantID: tenantID,
	}
	mock.lockWithTenant.Lock()
	mock.calls.WithTenant = append(mock.calls.WithTenant, callInfo)
	mock.lockWithTenant.Unlock()
	return mock.WithTenantFunc(tenantID)
}

// WithTenantCalls gets all the calls that were made to WithTenant.
// Check the length with:
//
//	len(mockedCLI.WithTenantCalls())
func (mock *CLIMock) WithTenantCalls() []struct {
	TenantID string
} {
	var calls []struct {
		TenantID string
	}
	mock.lockWithTenant.RLock()
	calls = mock.calls.WithTenant
	mock.lockWithTenant.RUnlock()
	return calls
}
