version: 2
project_name: azctx
builds:
  - id: linux
    env: [ CGO_ENABLED=0, GOEXPERIMENT=jsonv2 ]
    main: .
    ldflags:
      - -s -w -X main.version={{ .Tag }}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: darwin-windows
    env: [ CGO_ENABLED=0, GOEXPERIMENT=jsonv2 ]
    main: .
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
dockers_v2:
  - ids:
      - linux
    images:
      - "ghcr.io/lvlcn-t/azctx"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "{{ .ProjectName }}"
      "org.opencontainers.image.url": "https://lvlcn-t.dev"
      "org.opencontainers.image.source": "https://github.com/lvlcn-t/azctx"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Timestamp }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"

# nfpms:
#   - maintainer: lvlcn-t <75443136+lvlcn-t@users.noreply.github.com>
#     description: |-
#       #
#     homepage: https://github.com/lvlcn-t
#     license: MIT
#     formats:
#       - deb
#       - rpm
#       - apk
