version: 2
project_name: azctx

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - sh -c "GOEXPERIMENT=jsonv2 go generate ./..."
    - sh -c "GOEXPERIMENT=jsonv2 go mod tidy"
    - mkdir -p completions
    - sh -c "GOEXPERIMENT=jsonv2 go run . completion zsh > completions/azctx.zsh"
    - sh -c "GOEXPERIMENT=jsonv2 go run . completion bash > completions/azctx.bash"
    - sh -c "GOEXPERIMENT=jsonv2 go run . completion fish > completions/azctx.fish"

builds:
  - id: linux
    env: [CGO_ENABLED=0, GOEXPERIMENT=jsonv2]
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: darwin-windows
    env: [CGO_ENABLED=0, GOEXPERIMENT=jsonv2]
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: azctx
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end -}}
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: azctx
    ids:
      - azctx
    repository:
      owner: lvlcn-t
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_msg_template: "feat: update {{ .ProjectName }} to {{ .Tag }}"
    commit_author:
      name: lvlcn-t
      email: 75443136+lvlcn-t@users.noreply.github.com

    homepage: https://github.com/lvlcn-t/azctx
    description: Faster way to switch between tenants and subscriptions with az
    license: MIT
    binaries:
      - azctx
    dependencies:
      - formula: azure-cli
    url:
      verified: github.com/lvlcn-t/azctx/releases/download
    completions:
      bash: completions/azctx.bash
      zsh: completions/azctx.zsh
      fish: completions/azctx.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
          end
    zap:
      trash:
        - "~/Library/Application Support/azctx"

dockers_v2:
  - ids:
      - linux
    images:
      - ghcr.io/lvlcn-t/azctx
    tags:
      - latest
      - "{{ .Tag }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Faster way to switch between tenants and subscriptions with az"
      "org.opencontainers.image.url": "https://lvlcn-t.dev"
      "org.opencontainers.image.source": "https://github.com/lvlcn-t/azctx"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Timestamp }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"
