version: 2
project_name: azctx
snapshot:
  version_template: "commit-{{ .ShortCommit }}"
builds:
  - env: [ CGO_ENABLED=0, GOEXPERIMENT=jsonv2 ]
    main: .
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers_v2:
  - images:
      - "ghcr.io/lvlcn-t/azctx"
    tags:
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "This is a pre-release version. Do not use this in production!"
      "org.opencontainers.image.url": "https://lvlcn-t.dev"
      "org.opencontainers.image.source": "https://github.com/lvlcn-t/azctx"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Timestamp }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"
