// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wif

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked Provider
//		mockedProvider := &ProviderMock{
//			AcquireTokenFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the AcquireToken method")
//			},
//		}
//
//		// use mockedProvider in code that requires Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// AcquireTokenFunc mocks the AcquireToken method.
	AcquireTokenFunc func(ctx context.Context) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// AcquireToken holds details about calls to the AcquireToken method.
		AcquireToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAcquireToken sync.RWMutex
}

// AcquireToken calls AcquireTokenFunc.
func (mock *ProviderMock) AcquireToken(ctx context.Context) (string, error) {
	if mock.AcquireTokenFunc == nil {
		panic("ProviderMock.AcquireTokenFunc: method is nil but Provider.AcquireToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAcquireToken.Lock()
	mock.calls.AcquireToken = append(mock.calls.AcquireToken, callInfo)
	mock.lockAcquireToken.Unlock()
	return mock.AcquireTokenFunc(ctx)
}

// AcquireTokenCalls gets all the calls that were made to AcquireToken.
// Check the length with:
//
//	len(mockedProvider.AcquireTokenCalls())
func (mock *ProviderMock) AcquireTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAcquireToken.RLock()
	calls = mock.calls.AcquireToken
	mock.lockAcquireToken.RUnlock()
	return calls
}
