// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package keyvault

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			GetSecretFunc: func(ctx context.Context, ref Reference) (string, error) {
//				panic("mock out the GetSecret method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// GetSecretFunc mocks the GetSecret method.
	GetSecretFunc func(ctx context.Context, ref Reference) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetSecret holds details about calls to the GetSecret method.
		GetSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref Reference
		}
	}
	lockGetSecret sync.RWMutex
}

// GetSecret calls GetSecretFunc.
func (mock *ClientMock) GetSecret(ctx context.Context, ref Reference) (string, error) {
	if mock.GetSecretFunc == nil {
		panic("ClientMock.GetSecretFunc: method is nil but Client.GetSecret was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref Reference
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetSecret.Lock()
	mock.calls.GetSecret = append(mock.calls.GetSecret, callInfo)
	mock.lockGetSecret.Unlock()
	return mock.GetSecretFunc(ctx, ref)
}

// GetSecretCalls gets all the calls that were made to GetSecret.
// Check the length with:
//
//	len(mockedClient.GetSecretCalls())
func (mock *ClientMock) GetSecretCalls() []struct {
	Ctx context.Context
	Ref Reference
} {
	var calls []struct {
		Ctx context.Context
		Ref Reference
	}
	mock.lockGetSecret.RLock()
	calls = mock.calls.GetSecret
	mock.lockGetSecret.RUnlock()
	return calls
}
